import { ROUTES } from "./routes";

// Navigation Menu Data
export const navigationMenuData = {
  topItems: [
    {
      id: "dashboard",
      label: "لوحة التحكم",
      icon: "/img/side-icons-1.svg",
      isActive: false,
      hasBackground: false,
      href: ROUTES.DASHBOARD,
    },
    {
      id: "wallet",
      label: "محفظــــــــــــتي",
      icon: "/img/side-icons-6.svg",
      hasBackground: false,
      href: ROUTES.WALLET,
    },
  ],
  sections: [
    {
      title: "المــــــــــــــــــــــــــــــوارد",
      items: [
        {
          id: "drivers",
          label: "الســـــــــــائقين",
          icon: "/img/side-icons-3.svg",
          hasBackground: false,
          href: ROUTES.DRIVERS,
        },
        {
          id: "cars",
          label: "السيـــــــــــــارات",
          icon: "/img/side-icons-4.svg",
          href: ROUTES.CARS,
        },
      ],
    },
    {
      title: "التقاريــــــــــــــــــــــــــــــر",
      items: [
        {
          id: "sales-report",
          label: "تقرير المبيعات",
          icon: "/img/side-icons-5.svg",
          href: ROUTES.FINANCIAL_REPORTS,
        },
        {
          id: "wallet-report",
          label: "تقرير المحفظة",
          icon: "/img/side-icons-6.svg",
          href: ROUTES.WALLET_REPORTS,
        },
      ],
    },
    {
      title: "المتجر والاشتراكات",
      items: [
        {
          id: "store",
          label: "المتجر",
          icon: "/img/side-icons-10.svg",
          href: ROUTES.STORE,
        },
        {
          id: "subscriptions",
          label: "اشتراكاتي",
          icon: "/img/side-icons-11.svg",
          href: ROUTES.SUBSCRIPTIONS,
        },
      ],
    },
  ],
  bottomItems: [
    {
      id: "fuel-delivery",
      label: "طلبات توصيل الوقود",
      icon: "/img/side-icons-7.svg",
      href: ROUTES.FUEL_DELIVERY,
    },
    {
      id: "stations",
      label: "محطات البترول",
      icon: "/img/side-icons-8.svg",
      href: ROUTES.PEROLIFE_STATION_LOCATIONS,
    },
    {
      id: "invoices",
      label: "الفواتير",
      icon: "/img/side-icons-5.svg",
      href: ROUTES.INVOICES,
    },
    {
      id: "refund-requests",
      label: "طلبات الاسترداد",
      icon: "/img/side-icons-10.svg",
      href: ROUTES.REFUND_REQUESTS,
    },
    {
      id: "charge-requests",
      label: "طلبات الشحن",
      icon: "/img/side-icons-11.svg",
      href: ROUTES.CHARGE_REQUESTS,
    },
  ],
};

// Service Distributer Navigation Menu Data
export const serviceDistributerNavigationMenuData = {
  topItems: [
    {
      id: "dashboard",
      label: "لوحة التحكم",
      icon: "/src/assets/imgs/icons/dashboard.svg",
      isActive: false,
      hasBackground: false,
      href: ROUTES.SERVICE_DISTRIBUTER_DASHBOARD,
    },
  ],
  sections: [
    {
      title: "موارد المركز",
      items: [
        {
          id: "workers",
          label: "عمال المحطـــــات",
          icon: "/src/assets/imgs/icons/user-group.svg",
          hasBackground: false,
          href: ROUTES.STATION_WORKERS,
        },
        {
          id: "stations",
          label: "المحطــــــات",
          icon: "/src/assets/imgs/icons/petrol-station.svg",
          href: ROUTES.STATIONS,
        },
      ],
    },
  ],
  bottomItems: [
    {
      id: "fuel-station-requests",
      label: "طلبات محطـــات الوقود",
      icon: "/src/assets/imgs/icons/document-clock.svg",
      href: ROUTES.FUEL_STATION_REQUESTS,
    },
    {
      id: "financial-reports",
      label: "التقارير المالية",
      icon: "/src/assets/imgs/icons/analytics.svg",
      href: ROUTES.SERVICE_DISTRIBUTER_FINANCIAL_REPORTS,
    },
    {
      id: "station-locations",
      label: "مواقع المحطات",
      icon: "/src/assets/imgs/icons/location-pin.svg",
      href: ROUTES.SERVICE_DISTRIBUTER_STATION_LOCATIONS,
    },
    {
      id: "invoices",
      label: "الفواتيــــــــــــر",
      icon: "/src/assets/imgs/icons/invoice.svg",
      href: ROUTES.SERVICE_DISTRIBUTER_INVOICES,
    },
    {
      id: "charge-requests",
      label: "الدعم الفني",
      icon: "/img/side-icons-11.svg",
      href: ROUTES.CHARGE_REQUESTS,
    },
  ],
};

// Admin Dashboard Navigation Menu Data
export const adminNavigationMenuData = {
  topItems: [
    {
      id: "dashboard",
      label: "لوحة التحكم",
      icon: "/img/side-icons-1.svg",
      isActive: false,
      hasBackground: false,
      href: ROUTES.ADMIN_DASHBOARD,
    },
  ],
  sections: [
    {
      title: "المستخدمين",
      items: [
        {
          id: "supervisors",
          label: "المشرفين",
          icon: "/img/side-icons-3.svg",
          hasBackground: false,
          href: ROUTES.SUPERVISORS,
        },
        {
          id: "companies",
          label: "الشركات",
          icon: "/img/side-icons-7.svg",
          href: ROUTES.COMPANIES,
        },
        {
          id: "people",
          label: "الافراد",
          icon: "/img/side-icons-7.svg",
          href: ROUTES.INDIVIDUALS,
        },
        {
          id: "service-providers",
          label: "مزودي الخدمة",
          icon: "/img/side-icons-7.svg",
          href: ROUTES.SERVICE_PROVIDERS,
        },
      ],
    },
    {
      title: "موارد بترولايف",
      items: [
        {
          id: "petrolife-drivers",
          label: "قائدو مركبات بترولايف",
          icon: "/img/side-icons-3.svg",
          hasBackground: false,
          href: ROUTES.PETROLIFE_DRIVERS,
        },
        {
          id: "petrolife-representatives",
          label: "مندوبو بترولايف",
          icon: "/img/side-icons-7.svg",
          href: ROUTES.PETROLIFE_REPRESENTATIVES,
        },
        {
          id: "petrolife-cars",
          label: "مركبات بترولايف",
          icon: "/img/side-icons-7.svg",
          href: ROUTES.PETROLIFE_CARS,
        },
        {
          id: "petrolife-products",
          label: "منتجات بترولايف",
          icon: "/img/side-icons-7.svg",
          href: ROUTES.PETROLIFE_PRODUCTS,
        },
        {
          id: "petrolife-coupons",
          label: "كوبونات بترولايف",
          icon: "/img/side-icons-7.svg",
          href: ROUTES.PETROLIFE_COUPONS,
        },
      ],
    },
    {
      title: "الطلبات",
      items: [
        {
          id: "wallet-requests",
          label: "طلبات المحافظ",
          icon: "/img/side-icons-3.svg",
          hasBackground: false,
          href: ROUTES.WALLET_REQUESTS,
        },
        {
          id: "fuel-delivery-requests",
          label: "طلبات توصيل الوقود",
          icon: "/img/side-icons-7.svg",
          href: ROUTES.FUEL_DELIVERY_REQUESTS,
        },
      ],
    },
    {
      title: "التقارير",
      items: [
        {
          id: "admin-financial-reports",
          label: "تقارير المبيعات",
          icon: "/img/side-icons-3.svg",
          hasBackground: false,
          href: ROUTES.ADMIN_FINANCIAL_REPORTS,
        },
        {
          id: "admin-invoice-reports",
          label: "تقارير الفواتير",
          icon: "/img/side-icons-7.svg",
          href: ROUTES.ADMIN_INVOICE_REPORTS,
        },
        {
          id: "admin-service-provider-reports",
          label: "تقارير مزودي الخدمة",
          icon: "/img/side-icons-7.svg",
          href: ROUTES.ADMIN_SERVICE_PROVIDER_REPORTS,
        },
        {
          id: "admin-representative-reports",
          label: "تقارير المندوبين",
          icon: "/img/side-icons-7.svg",
          href: ROUTES.ADMIN_REPRESENTATIVE_REPORTS,
        },
        {
          id: "admin-wallet-reports",
          label: "تقارير المحفظة",
          icon: "/img/side-icons-7.svg",
          href: ROUTES.ADMIN_WALLET_REPORTS,
        },
      ],
    },
    {
      title: "الثوابت",
      items: [
        {
          id: "admin-countries",
          label: "البلدان",
          icon: "/img/side-icons-3.svg",
          hasBackground: false,
          href: ROUTES.ADMIN_COUNTRIES,
        },
        {
          id: "admin-cars",
          label: "المركبات",
          icon: "/img/side-icons-3.svg",
          hasBackground: false,
          href: ROUTES.ADMIN_CARS,
        },
        {
          id: "admin-categories",
          label: "التصنيفات",
          icon: "/img/side-icons-3.svg",
          hasBackground: false,
          href: ROUTES.ADMIN_CATEGORIES,
        },
      ],
    },
  ],
  bottomItems: [
    {
      id: "application-services",
      label: "خدمات التطبيق",
      icon: "/img/side-icons-7.svg",
      href: ROUTES.APPLICATION_SERVICES,
    },
    {
      id: "default-accounts",
      label: "الحسابات الافتراضية",
      icon: "/img/side-icons-7.svg",
      href: ROUTES.DEFAULT_ACCOUNTS,
    },
    {
      id: "advertisements",
      label: "الإعلانات",
      icon: "/img/side-icons-7.svg",
      href: ROUTES.ADVERTISEMENTS,
    },
    {
      id: "special-notifications",
      label: "الاشعارات المخصصة",
      icon: "/img/side-icons-7.svg",
      href: ROUTES.SPECIAL_NOTIFICATIONS,
    },
    {
      id: "admin-subscriptions",
      label: "الاشتراكات",
      icon: "/img/side-icons-7.svg",
      href: ROUTES.ADMIN_SUBSCRIPTIONS,
    },
    {
      id: "admin-communication-policies",
      label: "وسائل التواصل & السياسة",
      icon: "/img/side-icons-7.svg",
      href: ROUTES.ADMIN_COMMUNICATION_POLICIES,
    },
  ],
  anotherSections: [
    {
      title: "الدعم الفني",
      items: [
        {
          id: "faq",
          label: "الاسئلة الشائعة",
          icon: "/img/side-icons-3.svg",
          hasBackground: false,
          href: ROUTES.FAQ,
        },
        {
          id: "customer-messages",
          label: "رسائل العملاء",
          icon: "/img/side-icons-7.svg",
          href: ROUTES.CUSTOMER_MESSAGES,
        },
      ],
    },
  ],
};

// User Information
export const userInfo = {
  name: "الشركة المتحدة العالمية",
  email: "hesham@gmail.com",
  avatar: "/img/image-2.png",
};

// Transaction Data
export const transactionData = [
  {
    id: "21A254",
    type: "وقود 91",
    driver: "أحمد محمد",
    date: "21 فبراير 2025 - 5:05 ص",
    amount: 20,
    cumulative: 200,
  },
  {
    id: "21A254",
    type: "منتج",
    driver: "--",
    date: "21 فبراير 2025 - 5:05 ص",
    amount: 20,
    cumulative: 180,
  },
  {
    id: "21A254",
    type: "وقود 91",
    driver: "أحمد محمد",
    date: "21 فبراير 2025 - 5:05 ص",
    amount: 20,
    cumulative: 160,
  },
  {
    id: "21A254",
    type: "وقود 91",
    driver: "أحمد محمد",
    date: "21 فبراير 2025 - 5:05 ص",
    amount: 20,
    cumulative: 140,
  },
  {
    id: "21A254",
    type: "وقود 91",
    driver: "أحمد محمد",
    date: "21 فبراير 2025 - 5:05 ص",
    amount: 20,
    cumulative: 120,
  },
  {
    id: "21A254",
    type: "وقود 91",
    driver: "أحمد محمد",
    date: "21 فبراير 2025 - 5:05 ص",
    amount: 20,
    cumulative: 100,
  },
  {
    id: "21A254",
    type: "وقود 91",
    driver: "أحمد محمد",
    date: "21 فبراير 2025 - 5:05 ص",
    amount: 20,
    cumulative: 80,
  },
  {
    id: "21A254",
    type: "وقود 91",
    driver: "أحمد محمد",
    date: "21 فبراير 2025 - 5:05 ص",
    amount: 20,
    cumulative: 60,
  },
  {
    id: "21A254",
    type: "وقود 91",
    driver: "أحمد محمد",
    date: "21 فبراير 2025 - 5:05 ص",
    amount: 20,
    cumulative: 40,
  },
  {
    id: "21A254",
    type: "وقود 91",
    driver: "أحمد محمد",
    date: "21 فبراير 2025 - 5:05 ص",
    amount: 20,
    cumulative: 20,
  },
];

// Wallet Reports Transaction Data
export const walletReportsTransactionData = [
  {
    id: "21A254",
    operationName: "تحويل بنكي",
    operationType: "تغذية محفظة",
    date: "21 فبراير 2025 - 5:05 ص",
    balance: "21536",
    debit: "",
  },
  {
    id: "21A254",
    operationName: "وقود",
    operationType: "فاتورة",
    date: "21 فبراير 2025 - 5:05 ص",
    balance: "21536",
    debit: "",
  },
  {
    id: "21A254",
    operationName: "اشتراك مركبات",
    operationType: "استرداد",
    date: "21 فبراير 2025 - 5:05 ص",
    balance: "21536",
    debit: "20",
  },
  {
    id: "21A254",
    operationName: "استرداد",
    operationType: "تغذية محفظة",
    date: "21 فبراير 2025 - 5:05 ص",
    balance: "21536",
    debit: "20",
  },
  {
    id: "21A254",
    operationName: "تحويل بنكي",
    operationType: "تغذية محفظة",
    date: "21 فبراير 2025 - 5:05 ص",
    balance: "21536",
    debit: "20",
  },
  {
    id: "21A254",
    operationName: "تحويل بنكي",
    operationType: "تغذية محفظة",
    date: "21 فبراير 2025 - 5:05 ص",
    balance: "21536",
    debit: "20",
  },
  {
    id: "21A254",
    operationName: "تحويل بنكي",
    operationType: "تغذية محفظة",
    date: "21 فبراير 2025 - 5:05 ص",
    balance: "21536",
    debit: "20",
  },
  {
    id: "21A254",
    operationName: "تحويل بنكي",
    operationType: "تغذية محفظة",
    date: "21 فبراير 2025 - 5:05 ص",
    balance: "21536",
    debit: "20",
  },
  {
    id: "21A254",
    operationName: "تحويل بنكي",
    operationType: "تغذية محفظة",
    date: "21 فبراير 2025 - 5:05 ص",
    balance: "21536",
    debit: "20",
  },
  {
    id: "21A254",
    operationName: "تحويل بنكي",
    operationType: "تغذية محفظة",
    date: "21 فبراير 2025 - 5:05 ص",
    balance: "21536",
    debit: "20",
  },
];

// Workers Data (Station Workers)
export const workersData = [
  {
    id: 1,
    driverCode: "W21A254",
    driverName: "أحمد محمد",
    phone: "00965284358",
    emailAddress: "ahmed.mohamed@petrolife.com",
    station: "محطة الرياض المركزية",
    accountStatus: { active: true, text: "مفعل" },
  },
  {
    id: 2,
    driverCode: "W21A255",
    driverName: "محمد أحمد",
    phone: "00965284359",
    emailAddress: "mohamed.ahmed@petrolife.com",
    station: "محطة جدة الشمالية",
    accountStatus: { active: true, text: "مفعل" },
  },
  {
    id: 3,
    driverCode: "W21A256",
    driverName: "علي حسن",
    phone: "00965284360",
    emailAddress: "ali.hassan@petrolife.com",
    station: "محطة الدمام",
    accountStatus: { active: true, text: "مفعل" },
  },
  {
    id: 4,
    driverCode: "W21A257",
    driverName: "حسن علي",
    phone: "00965284361",
    emailAddress: "hassan.ali@petrolife.com",
    station: "محطة مكة",
    accountStatus: { active: true, text: "مفعل" },
  },
  {
    id: 5,
    driverCode: "W21A258",
    driverName: "محمود سعد",
    phone: "00965284362",
    emailAddress: "mahmoud.saad@petrolife.com",
    station: "محطة المدينة المنورة",
    accountStatus: { active: true, text: "مفعل" },
  },
  {
    id: 6,
    driverCode: "W21A259",
    driverName: "سعد محمود",
    phone: "00965284363",
    emailAddress: "saad.mahmoud@petrolife.com",
    station: "محطة الخبر",
    accountStatus: { active: true, text: "مفعل" },
  },
  {
    id: 7,
    driverCode: "W21A260",
    driverName: "يوسف إبراهيم",
    phone: "00965284364",
    emailAddress: "yousef.ibrahim@petrolife.com",
    station: "محطة الطائف",
    accountStatus: { active: true, text: "مفعل" },
  },
  {
    id: 8,
    driverCode: "W21A261",
    driverName: "إبراهيم يوسف",
    phone: "00965284365",
    emailAddress: "ibrahim.yousef@petrolife.com",
    station: "محطة أبها",
    accountStatus: { active: false, text: "معطل" },
  },
  {
    id: 9,
    driverCode: "W21A262",
    driverName: "خالد عبدالله",
    phone: "00965284366",
    emailAddress: "khaled.abdullah@petrolife.com",
    station: "محطة القصيم",
    accountStatus: { active: false, text: "معطل" },
  },
  {
    id: 10,
    driverCode: "W21A263",
    driverName: "عبدالله خالد",
    phone: "00965284367",
    emailAddress: "abdullah.khaled@petrolife.com",
    station: "محطة حائل",
    accountStatus: { active: false, text: "معطل" },
  },
];

// Stations Data
export const stationsData = [
  {
    id: 1,
    stationCode: "S21A001",
    stationName: "محطة الرياض المركزية",
    location: "الرياض، حي العليا",
    city: "الرياض",
    phone: "00966112345678",
    emailAddress: "riyadh.central@petrolife.com",
    managerName: "عبدالعزيز السعيد",
    fuelTypes: ["بنزين 91", "ديزل"],
    workersCount: 12,
    accountStatus: { active: true, text: "مفعل" },
  },
  {
    id: 2,
    stationCode: "S21A002",
    stationName: "محطة جدة الشمالية",
    location: "جدة، حي الروضة",
    city: "جدة",
    phone: "00966122345678",
    emailAddress: "jeddah.north@petrolife.com",
    managerName: "محمد الغامدي",
    fuelTypes: ["بنزين 91", "بنزين 95"],
    workersCount: 10,
    accountStatus: { active: true, text: "مفعل" },
  },
  {
    id: 3,
    stationCode: "S21A003",
    stationName: "محطة الدمام",
    location: "الدمام، حي الفيصلية",
    city: "الدمام",
    phone: "00966132345678",
    emailAddress: "dammam@petrolife.com",
    managerName: "فهد الخالدي",
    fuelTypes: ["بنزين 91", "ديزل"],
    workersCount: 8,
    accountStatus: { active: true, text: "مفعل" },
  },
  {
    id: 4,
    stationCode: "S21A004",
    stationName: "محطة مكة",
    location: "مكة المكرمة، حي العزيزية",
    city: "مكة",
    phone: "00966142345678",
    emailAddress: "makkah@petrolife.com",
    managerName: "خالد الشريف",
    fuelTypes: ["بنزين 91", "ديزل"],
    workersCount: 15,
    accountStatus: { active: true, text: "مفعل" },
  },
  {
    id: 5,
    stationCode: "S21A005",
    stationName: "محطة المدينة المنورة",
    location: "المدينة المنورة، حي العيون",
    city: "المدينة المنورة",
    phone: "00966152345678",
    emailAddress: "madinah@petrolife.com",
    managerName: "سعد الأنصاري",
    fuelTypes: ["بنزين 91", "بنزين 95", "ديزل"],
    workersCount: 11,
    accountStatus: { active: true, text: "مفعل" },
  },
  {
    id: 6,
    stationCode: "S21A006",
    stationName: "محطة الخبر",
    location: "الخبر، حي الكورنيش",
    city: "الخبر",
    phone: "00966162345678",
    emailAddress: "khobar@petrolife.com",
    managerName: "ماجد العتيبي",
    fuelTypes: ["بنزين 91", "بنزين 95"],
    workersCount: 9,
    accountStatus: { active: false, text: "معطل" },
  },
  {
    id: 7,
    stationCode: "S21A007",
    stationName: "محطة الطائف",
    location: "الطائف، حي الشهداء",
    city: "الطائف",
    phone: "00966172345678",
    emailAddress: "taif@petrolife.com",
    managerName: "يوسف الزهراني",
    fuelTypes: ["بنزين 91", "ديزل"],
    workersCount: 7,
    accountStatus: { active: true, text: "مفعل" },
  },
  {
    id: 8,
    stationCode: "S21A008",
    stationName: "محطة أبها",
    location: "أبها، حي المنسك",
    city: "أبها",
    phone: "00966182345678",
    emailAddress: "abha@petrolife.com",
    managerName: "إبراهيم عسيري",
    fuelTypes: ["بنزين 91", "بنزين 95", "ديزل"],
    workersCount: 6,
    accountStatus: { active: false, text: "معطل" },
  },
  {
    id: 9,
    stationCode: "S21A009",
    stationName: "محطة القصيم",
    location: "بريدة، حي الصفراء",
    city: "القصيم",
    phone: "00966192345678",
    emailAddress: "qassim@petrolife.com",
    managerName: "خالد المطيري",
    fuelTypes: ["بنزين 91", "بنزين 95"],
    workersCount: 8,
    accountStatus: { active: false, text: "معطل" },
  },
  {
    id: 10,
    stationCode: "S21A010",
    stationName: "محطة حائل",
    location: "حائل، حي السمراء",
    city: "حائل",
    phone: "00966202345678",
    emailAddress: "hail@petrolife.com",
    managerName: "عبدالله الشمري",
    fuelTypes: ["بنزين 91", "ديزل"],
    workersCount: 5,
    accountStatus: { active: true, text: "مفعل" },
  },
];

// Car Data
// Drivers Data
export const driversData = [
  {
    id: 1,
    driverCode: "21A254",
    driverName: "أحمد محمد",
    phone: "00965284358",
    address: "12 ش المنيل ، مصر",
    fuelType: "بنزين 91",
    financialValue: "1600 / 1400",
    carNumber: "2145224",
    carCategory: { text: "صغيرة", icon: "/img/component-4-11.svg" },
    accountStatus: { active: true, text: "مفعل" },
  },
  {
    id: 2,
    driverCode: "21A255",
    driverName: "محمد أحمد",
    phone: "00965284359",
    address: "15 ش المعادي ، مصر",
    fuelType: "بنزين 91",
    financialValue: "1600 / 1000",
    carNumber: "2145225",
    carCategory: { text: "كبيرة", icon: "/img/component-4-4.svg" },
    accountStatus: { active: true, text: "مفعل" },
  },
  {
    id: 3,
    driverCode: "21A256",
    driverName: "علي حسن",
    phone: "00965284360",
    address: "20 ش الزمالك ، مصر",
    fuelType: "بنزين 91",
    financialValue: "1600 / 1400",
    carNumber: "2145226",
    carCategory: { text: "متوسطة", icon: "/img/component-4-5.svg" },
    accountStatus: { active: true, text: "مفعل" },
  },
  {
    id: 4,
    driverCode: "21A257",
    driverName: "حسن علي",
    phone: "00965284361",
    address: "25 ش المهندسين ، مصر",
    fuelType: "بنزين 91",
    financialValue: "-- / 1400",
    carNumber: "2145227",
    carCategory: { text: "VIP", icon: "/img/component-4-6.svg" },
    accountStatus: { active: true, text: "مفعل" },
  },
  {
    id: 5,
    driverCode: "21A258",
    driverName: "محمود سعد",
    phone: "00965284362",
    address: "30 ش الدقي ، مصر",
    fuelType: "بنزين 91",
    financialValue: "1600 / 1400",
    carNumber: "2145228",
    carCategory: { text: "صغيرة", icon: "/img/component-4-11.svg" },
    accountStatus: { active: true, text: "مفعل" },
  },
  {
    id: 6,
    driverCode: "21A259",
    driverName: "سعد محمود",
    phone: "00965284363",
    address: "35 ش العجوزة ، مصر",
    fuelType: "بنزين 91",
    financialValue: "1600 / 1400",
    carNumber: "--",
    carCategory: { text: "--", icon: null },
    accountStatus: { active: true, text: "مفعل" },
  },
  {
    id: 7,
    driverCode: "21A260",
    driverName: "يوسف إبراهيم",
    phone: "00965284364",
    address: "40 ش المقطم ، مصر",
    fuelType: "بنزين 91",
    financialValue: "1600 / 1400",
    carNumber: "2145229",
    carCategory: { text: "صغيرة", icon: "/img/component-4-11.svg" },
    accountStatus: { active: true, text: "مفعل" },
  },
  {
    id: 8,
    driverCode: "21A261",
    driverName: "إبراهيم يوسف",
    phone: "00965284365",
    address: "45 ش النزهة ، مصر",
    fuelType: "بنزين 91",
    financialValue: "1600 / 1400",
    carNumber: "2145230",
    carCategory: { text: "صغيرة", icon: "/img/component-4-11.svg" },
    accountStatus: { active: false, text: "معطل" },
  },
  {
    id: 9,
    driverCode: "21A262",
    driverName: "خالد عبدالله",
    phone: "00965284366",
    address: "50 ش التجمع ، مصر",
    fuelType: "بنزين 91",
    financialValue: "1600 / 1400",
    carNumber: "2145231",
    carCategory: { text: "صغيرة", icon: "/img/component-4-11.svg" },
    accountStatus: { active: false, text: "معطل" },
  },
  {
    id: 10,
    driverCode: "21A263",
    driverName: "عبدالله خالد",
    phone: "00965284367",
    address: "55 ش الشروق ، مصر",
    fuelType: "بنزين 91",
    financialValue: "1600 / 1400",
    carNumber: "2145232",
    carCategory: { text: "صغيرة", icon: "/img/component-4-11.svg" },
    accountStatus: { active: false, text: "معطل" },
  },
];

export const carData = [
  {
    id: 1,
    carNumber: "21A254",
    carName: "سيارة الطلبات",
    brand: "تيوتا",
    model: "كرولا",
    year: "2020",
    fuelType: "بنزين 91",
    category: { name: "صغيرة", icon: "/img/component-4-8.svg" },
    drivers: [
      {
        name: "محمد، مراد",
        avatar1: "/img/ellipse-17.svg",
        avatar2: "/img/ellipse-18.svg",
      },
    ],
  },
  {
    id: 2,
    carNumber: "21A254",
    carName: "سيارة الطلبات",
    brand: "تيوتا",
    model: "كرولا",
    year: "2020",
    fuelType: "بنزين 91",
    category: { name: "كبيرة", icon: "/img/component-4-1.svg" },
    drivers: [
      {
        name: "محمد، مراد، عبدالك..",
        avatar1: "/img/ellipse-17-1.svg",
        avatar2: "/img/ellipse-18-1.svg",
        avatar3: "/img/ellipse-19.svg",
      },
    ],
  },
  {
    id: 3,
    carNumber: "21A254",
    carName: "سيارة الطلبات",
    brand: "تيوتا",
    model: "كرولا",
    year: "2020",
    fuelType: "بنزين 91",
    category: { name: "متوسطة", icon: "/img/component-4-2.svg" },
    drivers: [{ name: "محمد", avatar1: "/img/ellipse-17-2.svg" }],
  },
  {
    id: 4,
    carNumber: "21A254",
    carName: "سيارة الطلبات",
    brand: "تيوتا",
    model: "كرولا",
    year: "2020",
    fuelType: "بنزين 91",
    category: { name: "VIP", icon: "/img/component-4-3.svg" },
    drivers: [
      {
        name: "محمد، مراد",
        avatar1: "/img/ellipse-17-3.svg",
        avatar2: "/img/ellipse-18-2.svg",
      },
    ],
  },
  {
    id: 5,
    carNumber: "21A254",
    carName: "سيارة الطلبات",
    brand: "تيوتا",
    model: "كرولا",
    year: "2020",
    fuelType: "بنزين 91",
    category: { name: "صغيرة", icon: "/img/component-4-8.svg" },
    drivers: [
      {
        name: "محمد، مراد",
        avatar1: "/img/ellipse-17-4.svg",
        avatar2: "/img/ellipse-18-3.svg",
      },
    ],
  },
  {
    id: 6,
    carNumber: "21A254",
    carName: "سيارة الطلبات",
    brand: "تيوتا",
    model: "كرولا",
    year: "2020",
    fuelType: "بنزين 91",
    category: null,
    drivers: [
      {
        name: "محمد، مراد",
        avatar1: "/img/ellipse-17-5.svg",
        avatar2: "/img/ellipse-18-4.svg",
      },
    ],
  },
  {
    id: 7,
    carNumber: "21A254",
    carName: "سيارة الطلبات",
    brand: "تيوتا",
    model: "كرولا",
    year: "2020",
    fuelType: "بنزين 91",
    category: { name: "صغيرة", icon: "/img/component-4-8.svg" },
    drivers: [
      {
        name: "محمد، مراد",
        avatar1: "/img/ellipse-17-6.svg",
        avatar2: "/img/ellipse-18-5.svg",
      },
    ],
  },
  {
    id: 8,
    carNumber: "21A254",
    carName: "سيارة الطلبات",
    brand: "تيوتا",
    model: "كرولا",
    year: "2020",
    fuelType: "بنزين 91",
    category: { name: "صغيرة", icon: "/img/component-4-8.svg" },
    drivers: [
      {
        name: "محمد، مراد",
        avatar1: "/img/ellipse-17-7.svg",
        avatar2: "/img/ellipse-18-6.svg",
      },
    ],
  },
  {
    id: 9,
    carNumber: "21A254",
    carName: "سيارة الطلبات",
    brand: "تيوتا",
    model: "كرولا",
    year: "2020",
    fuelType: "بنزين 91",
    category: { name: "صغيرة", icon: "/img/component-4-8.svg" },
    drivers: [
      {
        name: "محمد، مراد",
        avatar1: "/img/ellipse-17-8.svg",
        avatar2: "/img/ellipse-18-7.svg",
      },
    ],
  },
  {
    id: 10,
    carNumber: "21A254",
    carName: "سيارة الطلبات",
    brand: "تيوتا",
    model: "كرولا",
    year: "2020",
    fuelType: "بنزين 91",
    category: { name: "صغيرة", icon: "/img/component-4-8.svg" },
    drivers: [
      {
        name: "محمد، مراد",
        avatar1: "/img/ellipse-17-9.svg",
        avatar2: "/img/ellipse-18-8.svg",
      },
    ],
  },
];

// Financial Reports Data
export const financialReportsData = [
  {
    city: "الرياض",
    stationName: "محطة الصالح",
    date: "21 فبراير 2025 - 5:05 ص",
    operationNumber: "21536",
    quantity: "20",
    productName: "بنزين 91",
    productNumber: "21536",
    productType: "وقود",
    driverName: "أحمد محمد",
    driverCode: "21A254",
  },
  {
    city: "الرياض",
    stationName: "محطة الصالح",
    date: "21 فبراير 2025 - 5:05 ص",
    operationNumber: "21536",
    quantity: "20",
    productName: "بنزين 91",
    productNumber: "21536",
    productType: "وقود",
    driverName: "أحمد محمد",
    driverCode: "21A254",
  },
  {
    city: "الرياض",
    stationName: "محطة الصالح",
    date: "21 فبراير 2025 - 5:05 ص",
    operationNumber: "21536",
    quantity: "20",
    productName: "بنزين 91",
    productNumber: "21536",
    productType: "وقود",
    driverName: "أحمد محمد",
    driverCode: "21A254",
  },
  {
    city: "الرياض",
    stationName: "محطة الصالح",
    date: "21 فبراير 2025 - 5:05 ص",
    operationNumber: "21536",
    quantity: "20",
    productName: "بنزين 91",
    productNumber: "21536",
    productType: "وقود",
    driverName: "أحمد محمد",
    driverCode: "21A254",
  },
  {
    city: "الرياض",
    stationName: "محطة الصالح",
    date: "21 فبراير 2025 - 5:05 ص",
    operationNumber: "21536",
    quantity: "20",
    productName: "بنزين 91",
    productNumber: "21536",
    productType: "وقود",
    driverName: "أحمد محمد",
    driverCode: "21A254",
  },
  {
    city: "الرياض",
    stationName: "محطة الصالح",
    date: "21 فبراير 2025 - 5:05 ص",
    operationNumber: "21536",
    quantity: "20",
    productName: "بنزين 91",
    productNumber: "21536",
    productType: "وقود",
    driverName: "أحمد محمد",
    driverCode: "21A254",
  },
  {
    city: "الرياض",
    stationName: "محطة الصالح",
    date: "21 فبراير 2025 - 5:05 ص",
    operationNumber: "21536",
    quantity: "20",
    productName: "بنزين 91",
    productNumber: "21536",
    productType: "وقود",
    driverName: "أحمد محمد",
    driverCode: "21A254",
  },
  {
    city: "الرياض",
    stationName: "محطة الصالح",
    date: "21 فبراير 2025 - 5:05 ص",
    operationNumber: "21536",
    quantity: "20",
    productName: "بنزين 91",
    productNumber: "21536",
    productType: "وقود",
    driverName: "أحمد محمد",
    driverCode: "21A254",
  },
  {
    city: "الرياض",
    stationName: "محطة الصالح",
    date: "21 فبراير 2025 - 5:05 ص",
    operationNumber: "21536",
    quantity: "20",
    productName: "بنزين 91",
    productNumber: "21536",
    productType: "وقود",
    driverName: "أحمد محمد",
    driverCode: "21A254",
  },
  {
    city: "الرياض",
    stationName: "محطة الصالح",
    date: "21 فبراير 2025 - 5:05 ص",
    operationNumber: "21536",
    quantity: "20",
    productName: "بنزين 91",
    productNumber: "21536",
    productType: "وقود",
    driverName: "أحمد محمد",
    driverCode: "21A254",
  },
];

// Client Data
export const clientData = {
  phone: "00966254523658",
  commercialRecord: "GDHGD2543",
  clientName: "الشركة المتحدة العالمية",
  city: "الرياض",
  taxNumber: "245863564",
  clientCode: "21546354",
};

// User Data for Wallet Reports
export const userDataColumns = [
  {
    fields: [
      { label: "رقم الهاتف", value: "00966254523658" },
      { label: "المدينة", value: "الرياض" },
    ],
  },
  {
    fields: [
      { label: "السجل التجاري", value: "GDHGD2543" },
      { label: "الرقم الضريبي", value: "245863564" },
    ],
  },
  {
    fields: [
      { label: "اسم العميل", value: "الشركة المتحدة العالمية" },
      { label: "كود العميل", value: "21546354" },
    ],
  },
];

// Filter Options
export const filterOptions = {
  timePeriod: [{ label: "الكل", value: "all", icon: "/img/side-icons-2.svg" }],
  operationName: [
    { label: "الكل", value: "all", icon: "/img/side-icons-5.svg" },
  ],
  operationType: [
    { label: "الكل", value: "all", icon: "/img/side-icons-4.svg" },
  ],
  reportType: [
    { label: "تحليلي", value: "analytical", icon: "/img/side-icons-5.svg" },
  ],
};

// Financial Reports Filter Options
export const financialReportsFilterOptions = [
  { label: "الفترة الزمنية", value: "الكل", icon: "/img/side-icons-16.svg" },
  {
    label: "كود الســـــــــائق",
    value: "الكل",
    icon: "/img/side-icons-17.svg",
  },
  {
    label: "المديــــــــــــنة",
    value: "الكل",
    icon: "/img/side-icons-18.svg",
  },
  { label: "نوع المنتج", value: "الكل", icon: "/img/side-icons-19.svg" },
  { label: "نوع التقرير", value: "تحليلي", icon: "/img/side-icons-20.svg" },
];

// Fuel Data
export const fuelData = [
  {
    type: "ديزل",
    amount: "185 .L",
    color: "text-color-mode-text-icons-t-orange",
  },
  {
    type: "بنزين 95",
    amount: "548 .L",
    color: "text-color-mode-text-icons-t-red",
  },
  {
    type: "بنزين 91",
    amount: "845 .L",
    color: "text-color-mode-text-icons-t-green",
  },
];

// Service Distributer Financial Reports Filter Options
export const serviceDistributerFinancialReportsFilterOptions = [
  {
    label: "نوع التقرير",
    value: "تحليلي",
    icon: "/img/side-icons-20.svg",
    options: [
      { value: "تحليلي", label: "تحليلي" },
      { value: "ملخص", label: "ملخص" },
      { value: "تفصيلي", label: "تفصيلي" },
    ],
  },
  {
    label: "اسم المنتج",
    value: "الكل",
    icon: "/img/side-icons-19.svg",
    options: [
      { value: "الكل", label: "الكل" },
      { value: "بنزين 91", label: "بنزين 91" },
      { value: "بنزين 95", label: "بنزين 95" },
      { value: "ديزل", label: "ديزل" },
      { value: "زيت محرك", label: "زيت محرك" },
      { value: "سائل تبريد", label: "سائل تبريد" },
    ],
  },
  {
    label: "قائمة المحطات",
    value: "الكل",
    icon: "/img/side-icons-18.svg",
    options: [
      { value: "الكل", label: "الكل" },
      { value: "محطة الرياض المركزية", label: "محطة الرياض المركزية" },
      { value: "محطة جدة الشمالية", label: "محطة جدة الشمالية" },
      { value: "محطة الدمام", label: "محطة الدمام" },
      { value: "محطة مكة", label: "محطة مكة" },
    ],
  },
  {
    label: "المدينة",
    value: "الكل",
    icon: "/img/side-icons-17.svg",
    options: [
      { value: "الكل", label: "الكل" },
      { value: "الرياض", label: "الرياض" },
      { value: "جدة", label: "جدة" },
      { value: "الدمام", label: "الدمام" },
      { value: "مكة", label: "مكة" },
      { value: "المدينة المنورة", label: "المدينة المنورة" },
    ],
  },
  {
    label: "رقم العملية",
    value: "الكل",
    icon: "/img/side-icons-16.svg",
    options: [
      { value: "الكل", label: "الكل" },
      { value: "21A254", label: "21A254" },
      { value: "21A255", label: "21A255" },
      { value: "21A256", label: "21A256" },
      { value: "21A257", label: "21A257" },
      { value: "21A258", label: "21A258" },
    ],
  },
];

// Service Distributer Financial Reports Data
export const serviceDistributerFinancialReportsData = [
  {
    id: 1,
    productType: "وقود",
    productNumber: "21A254",
    productName: "بنزين 91",
    quantity: "20",
    value: "94",
    unit: "لتر",
    operationNumber: "21A254",
  },
  {
    id: 2,
    productType: "وقود",
    productNumber: "21A255",
    productName: "بنزين 95",
    quantity: "15",
    value: "78",
    unit: "لتر",
    operationNumber: "21A255",
  },
  {
    id: 3,
    productType: "وقود",
    productNumber: "21A256",
    productName: "ديزل",
    quantity: "25",
    value: "85",
    unit: "لتر",
    operationNumber: "21A256",
  },
  {
    id: 4,
    productType: "منتج",
    productNumber: "21A257",
    productName: "زيت محرك",
    quantity: "5",
    value: "120",
    unit: "لتر",
    operationNumber: "21A257",
  },
  {
    id: 5,
    productType: "وقود",
    productNumber: "21A258",
    productName: "بنزين 91",
    quantity: "30",
    value: "141",
    unit: "لتر",
    operationNumber: "21A258",
  },
  {
    id: 6,
    productType: "وقود",
    productNumber: "21A259",
    productName: "ديزل",
    quantity: "18",
    value: "61",
    unit: "لتر",
    operationNumber: "21A259",
  },
  {
    id: 7,
    productType: "منتج",
    productNumber: "21A260",
    productName: "سائل تبريد",
    quantity: "8",
    value: "96",
    unit: "لتر",
    operationNumber: "21A260",
  },
  {
    id: 8,
    productType: "وقود",
    productNumber: "21A261",
    productName: "بنزين 95",
    quantity: "22",
    value: "115",
    unit: "لتر",
    operationNumber: "21A261",
  },
  {
    id: 9,
    productType: "وقود",
    productNumber: "21A262",
    productName: "بنزين 91",
    quantity: "12",
    value: "56",
    unit: "لتر",
    operationNumber: "21A262",
  },
  {
    id: 10,
    productType: "منتج",
    productNumber: "21A263",
    productName: "زيت ناقل حركة",
    quantity: "3",
    value: "75",
    unit: "لتر",
    operationNumber: "21A263",
  },
];

// Invoices Data
export const invoicesData = [
  {
    id: 1,
    invoiceCode: "INV-2024-001",
    invoiceType: "فاتورة مبيعات",
    creationDate: "2024-10-01",
    vat: "150.00 ر.س",
    totalWithVat: "1,150.00 ر.س",
  },
  {
    id: 2,
    invoiceCode: "INV-2024-002",
    invoiceType: "فاتورة خدمات",
    creationDate: "2024-10-05",
    vat: "75.00 ر.س",
    totalWithVat: "575.00 ر.س",
  },
  {
    id: 3,
    invoiceCode: "INV-2024-003",
    invoiceType: "فاتورة مبيعات",
    creationDate: "2024-10-10",
    vat: "300.00 ر.س",
    totalWithVat: "2,300.00 ر.س",
  },
  {
    id: 4,
    invoiceCode: "INV-2024-004",
    invoiceType: "فاتورة مشتريات",
    creationDate: "2024-10-12",
    vat: "225.00 ر.س",
    totalWithVat: "1,725.00 ر.س",
  },
  {
    id: 5,
    invoiceCode: "INV-2024-005",
    invoiceType: "فاتورة خدمات",
    creationDate: "2024-10-14",
    vat: "180.00 ر.س",
    totalWithVat: "1,380.00 ر.س",
  },
  {
    id: 6,
    invoiceCode: "INV-2024-006",
    invoiceType: "فاتورة مبيعات",
    creationDate: "2024-10-15",
    vat: "90.00 ر.س",
    totalWithVat: "690.00 ر.س",
  },
  {
    id: 7,
    invoiceCode: "INV-2024-007",
    invoiceType: "فاتورة خدمات",
    creationDate: "2024-10-16",
    vat: "135.00 ر.س",
    totalWithVat: "1,035.00 ر.س",
  },
  {
    id: 8,
    invoiceCode: "INV-2024-008",
    invoiceType: "فاتورة مشتريات",
    creationDate: "2024-10-17",
    vat: "210.00 ر.س",
    totalWithVat: "1,610.00 ر.س",
  },
  {
    id: 9,
    invoiceCode: "INV-2024-009",
    invoiceType: "فاتورة مبيعات",
    creationDate: "2024-10-18",
    vat: "165.00 ر.س",
    totalWithVat: "1,265.00 ر.س",
  },
  {
    id: 10,
    invoiceCode: "INV-2024-010",
    invoiceType: "فاتورة خدمات",
    creationDate: "2024-10-19",
    vat: "195.00 ر.س",
    totalWithVat: "1,495.00 ر.س",
  },
];

// Fuel Station Requests Data
export const fuelStationRequestsData = [
  {
    id: 1,
    transactionNumber: "21A254",
    stationName: "الرياض",
    clientName: "هشام موسى",
    workerName: "هشام موسى",
    fuelType: "ديزل",
    totalLiters: "2",
    creationDate: "21 فبراير 2025 - 5:05 ص",
  },
  {
    id: 2,
    transactionNumber: "21A255",
    stationName: "الرياض",
    clientName: "هشام موسى",
    workerName: "هشام موسى",
    fuelType: "بنزين 91، بنزين 95",
    totalLiters: "4",
    creationDate: "21 فبراير 2025 - 5:05 ص",
  },
  {
    id: 3,
    transactionNumber: "21A256",
    stationName: "الرياض",
    clientName: "هشام موسى",
    workerName: "هشام موسى",
    fuelType: "بنزين 95",
    totalLiters: "2",
    creationDate: "21 فبراير 2025 - 5:05 ص",
  },
  {
    id: 4,
    transactionNumber: "21A257",
    stationName: "جدة",
    clientName: "أحمد محمد",
    workerName: "محمد أحمد",
    fuelType: "ديزل",
    totalLiters: "4",
    creationDate: "20 فبراير 2025 - 4:30 ص",
  },
  {
    id: 5,
    transactionNumber: "21A258",
    stationName: "الدمام",
    clientName: "علي حسن",
    workerName: "حسن علي",
    fuelType: "بنزين 91",
    totalLiters: "2",
    creationDate: "20 فبراير 2025 - 3:15 ص",
  },
  {
    id: 6,
    transactionNumber: "21A259",
    stationName: "مكة",
    clientName: "محمود سعد",
    workerName: "سعد محمود",
    fuelType: "بنزين 95",
    totalLiters: "4",
    creationDate: "19 فبراير 2025 - 6:45 ص",
  },
  {
    id: 7,
    transactionNumber: "21A260",
    stationName: "المدينة المنورة",
    clientName: "يوسف إبراهيم",
    workerName: "إبراهيم يوسف",
    fuelType: "ديزل",
    totalLiters: "2",
    creationDate: "19 فبراير 2025 - 2:20 ص",
  },
  {
    id: 8,
    transactionNumber: "21A261",
    stationName: "الخبر",
    clientName: "خالد عبدالله",
    workerName: "عبدالله خالد",
    fuelType: "بنزين 91، بنزين 95",
    totalLiters: "4",
    creationDate: "18 فبراير 2025 - 7:10 ص",
  },
  {
    id: 9,
    transactionNumber: "21A262",
    stationName: "الطائف",
    clientName: "فهد المطيري",
    workerName: "مطيري فهد",
    fuelType: "ديزل",
    totalLiters: "2",
    creationDate: "18 فبراير 2025 - 1:55 ص",
  },
  {
    id: 10,
    transactionNumber: "21A263",
    stationName: "أبها",
    clientName: "عبدالعزيز السعيد",
    workerName: "سعيد عبدالعزيز",
    fuelType: "بنزين 95",
    totalLiters: "4",
    creationDate: "17 فبراير 2025 - 8:30 ص",
  },
];

// Time Filters
export const timeFilters = [
  "اخر اسبوع",
  "اخر 30 يوم",
  "اخر 6 شهور",
  "اخر 12 شهر",
];

// Navigation Icons
export const navigationIcons = [
  {
    id: 1,
    src: "/img/component-1.svg",
    alt: "Component",
  },
  {
    id: 2,
    src: "/img/component-1-1.svg",
    alt: "Component",
  },
  {
    id: 3,
    vectors: [
      {
        src: "/img/vector.svg",
        alt: "Vector",
        className: "absolute w-2.5 h-2.5 top-1 left-1",
      },
      {
        src: "/img/vector-1.svg",
        alt: "Vector",
        className: "absolute w-[18px] h-[18px] top-0 left-0",
      },
    ],
  },
  { id: 4, text: "En" },
];
